blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://invite.vizality.com
    about: If you need help with anything, join our Discord support server and ask in the appropriated channel.